// Injects a small "who generated this" badge into a model-authored static
// page. The badge's content comes from the site's own registry/model-server
// discovery, never from the model's own output, so a model can't mislabel or
// omit its own attribution.
//
// Best-effort isolation: an inline <style> scoped to a unique id plus
// `!important` on every property. This is not bulletproof against a model's
// own `!important` rules or exact id collisions, but that risk is low and an
// iframe/shadow-DOM wrapper would reintroduce the shared chrome these pages
// are deliberately built without.

const BADGE_ID = 'rlab-provenance-badge';

export function injectProvenanceBadge(html, { provider, model, galleryUrl = '/cv/resumes' }) {
  const badge = `
<div id="${BADGE_ID}">
  <style>
    #${BADGE_ID} {
      all: initial !important;
      position: fixed !important;
      bottom: 12px !important;
      right: 12px !important;
      z-index: 2147483647 !important;
      font-family: ui-sans-serif, system-ui, sans-serif !important;
      font-size: 12px !important;
      line-height: 1.4 !important;
    }
    #${BADGE_ID} a {
      all: initial !important;
      display: inline-block !important;
      font-family: inherit !important;
      font-size: inherit !important;
      background: rgba(20, 20, 24, 0.86) !important;
      color: #fff !important;
      padding: 6px 10px !important;
      border-radius: 999px !important;
      text-decoration: none !important;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.25) !important;
    }
    #${BADGE_ID} a:hover {
      background: rgba(20, 20, 24, 1) !important;
    }
  </style>
  <a href="${galleryUrl}">Generated by ${escapeHtml(provider)} · ${escapeHtml(model)}</a>
</div>`;

  if (/<\/body>/i.test(html)) {
    return html.replace(/<\/body>/i, `${badge}\n</body>`);
  }
  return `${html}\n${badge}`;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}
